# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ved.proto

from googlepb.protobuf import descriptor as _descriptor
from googlepb.protobuf import message as _message
from googlepb.protobuf import reflection as _reflection
from googlepb.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ved.proto',
  package='ved',
  serialized_pb='\n\x0fproto/ved.proto\x12\x03ved\"k\n\x03Ved\x12\x13\n\x0bindex_boost\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x04\x12\x19\n\x11sub_link_position\x18\x05 \x01(\x04\x12\x17\n\x0fresult_position\x18\x06 \x01(\x04\x12\r\n\x05start\x18\x07 \x01(\x04')




_VED = _descriptor.Descriptor(
  name='Ved',
  full_name='ved.Ved',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_boost', full_name='ved.Ved.index_boost', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ved.Ved.type', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_link_position', full_name='ved.Ved.sub_link_position', index=2,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_position', full_name='ved.Ved.result_position', index=3,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='ved.Ved.start', index=4,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['Ved'] = _VED

class Ved(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VED

  # @@protoc_insertion_point(class_scope:ved.Ved)


# @@protoc_insertion_point(module_scope)
